import Link from "next/link";
import { FixtureBoard } from "@/components/fixture-board";
import { ProductShell } from "@/components/product-shell";
import styles from "./product.module.css";

export default function Home() {
  return (
    <ProductShell active="home">
      <main className={styles.page} id="main-content">
        <section className={styles.hero} aria-labelledby="hero-title">
          <div className={styles.heroCopy}>
            <div>
              <p className={styles.eyebrow}>Premier League prediction engine</p>
              <h1 id="hero-title">One league. Two timelines.</h1>
              <p className={styles.heroLead}>
                Every fixture receives one probabilistic forecast and one complete simulated
                match, locked 24 hours before kickoff. Then reality gets the final word.
              </p>
              <div className={styles.heroActions}>
                <Link className={styles.primaryButton} href="/fixtures">
                  View fixtures
                </Link>
                <Link className={styles.secondaryButton} href="/#method">
                  See the method
                </Link>
              </div>
            </div>
            <div className={styles.trustRow} aria-label="Forecast commitments">
              <span>No regeneration</span>
              <span>No bookmaker odds</span>
              <span>No fictional live data</span>
            </div>
          </div>
          <aside className={styles.enginePanel} aria-label="How the engine operates">
            <div className={styles.engineTop}>
              <span>Engine status</span>
              <strong>Method locked</strong>
            </div>
            <div className={styles.engineCore}>
              <div>
                <b>T-24</b>
                <p>
                  <strong>Forecast</strong>
                  <span>Expected score, outcome probabilities, lineup, and match statistics.</span>
                </p>
              </div>
              <div>
                <b>01:00</b>
                <p>
                  <strong>Replay</strong>
                  <span>The stored match unfolds at one fixed presentation speed for everyone.</span>
                </p>
              </div>
              <div>
                <b>FT</b>
                <p>
                  <strong>Evaluate</strong>
                  <span>Predictions remain visible and are measured against the real result.</span>
                </p>
              </div>
            </div>
            <div className={styles.engineBottom}>
              <span>Official outcome model</span>
              <strong>Phase 7 goals</strong>
            </div>
          </aside>
        </section>

        <section className={styles.section} aria-labelledby="fixtures-title">
          <header className={styles.sectionHeader}>
            <div>
              <p className={styles.eyebrow}>Canonical fixture feed</p>
              <h2 id="fixtures-title">Coming next</h2>
            </div>
            <p>
              Only real clubs and matches from the internal database appear here. If the source is
              unavailable, the site says so instead of substituting sample data.
            </p>
          </header>
          <FixtureBoard />
          <div className={styles.sectionActions}>
            <Link className={styles.secondaryButton} href="/fixtures">
              All fixtures
            </Link>
          </div>
        </section>

        <section className={styles.section} id="method" aria-labelledby="method-title">
          <header className={styles.sectionHeader}>
            <div>
              <p className={styles.eyebrow}>One transparent lifecycle</p>
              <h2 id="method-title">How it works</h2>
            </div>
            <p>
              The forecast is generated by the backend, never by a visitor pressing a button. One
              official version remains accountable from prediction through evaluation.
            </p>
          </header>
          <div className={styles.methodGrid}>
            <article className={styles.methodCard}>
              <span>01 / Before kickoff</span>
              <h3>Forecast at T-24</h3>
              <p>
                The scheduled worker freezes the available evidence and creates the official
                probabilities, expected lineup, score distribution, and statistics.
              </p>
            </article>
            <article className={styles.methodCard}>
              <span>02 / Stored once</span>
              <h3>Reveal the simulation</h3>
              <p>
                Events and the final score already exist. The page only reveals that immutable
                sequence over 60 seconds; there are no replay-speed or simulate controls.
              </p>
            </article>
            <article className={styles.methodCard}>
              <span>03 / After full time</span>
              <h3>Compare with reality</h3>
              <p>
                The forecast stays unchanged while the real result and real table update. Phase
                16B will make that comparison a first-class part of the product.
              </p>
            </article>
          </div>
        </section>

        <aside className={styles.promise}>
          <span>The Prem Engine promise</span>
          <p>
            A prediction that can be quietly rewritten is not a prediction. Every official match
            is locked, traceable, and judged against what actually happened.
          </p>
        </aside>
      </main>
    </ProductShell>
  );
}
