"""add ingestion audit and identity review

Revision ID: 43a723a183f9
Revises: 8867eff66966
Create Date: 2026-08-07 11:39:42.167265
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "43a723a183f9"
down_revision: str | None = "8867eff66966"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identity_review_cases",
        sa.Column("review_uuid", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "resolved", "dismissed", name="identity_review_status"),
            nullable=False,
        ),
        sa.Column("provider_name", sa.String(length=180), nullable=True),
        sa.Column("candidate_uuids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolved_uuid", sa.Uuid(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("review_uuid", name=op.f("pk_identity_review_cases")),
    )
    op.create_index(
        op.f("ix_identity_review_cases_status"), "identity_review_cases", ["status"], unique=False
    )
    op.create_index(
        "uq_identity_review_pending_external",
        "identity_review_cases",
        ["entity_type", "provider", "external_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "provider_requests",
        sa.Column("provider_request_uuid", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("endpoint", sa.String(length=240), nullable=False),
        sa.Column("query_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("reserved", "succeeded", "failed", name="provider_request_status"),
            nullable=False,
        ),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_status", sa.SmallInteger(), nullable=True),
        sa.Column("rate_limit", sa.Integer(), nullable=True),
        sa.Column("rate_remaining", sa.Integer(), nullable=True),
        sa.Column("rate_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_request_id", sa.String(length=160), nullable=True),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("provider_request_uuid", name=op.f("pk_provider_requests")),
    )
    op.create_index(
        op.f("ix_provider_requests_provider"), "provider_requests", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_provider_requests_status"), "provider_requests", ["status"], unique=False
    )
    op.create_table(
        "competition_external_references",
        sa.Column("reference_uuid", sa.Uuid(), nullable=False),
        sa.Column("competition_uuid", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_competition_id", sa.String(length=120), nullable=False),
        sa.Column("observed_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_uuid"],
            ["competitions.competition_uuid"],
            name=op.f("fk_competition_external_references_competition_uuid_competitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("reference_uuid", name=op.f("pk_competition_external_references")),
        sa.UniqueConstraint(
            "provider",
            "external_competition_id",
            name=op.f("uq_competition_external_references_provider"),
        ),
    )
    op.create_index(
        op.f("ix_competition_external_references_competition_uuid"),
        "competition_external_references",
        ["competition_uuid"],
        unique=False,
    )
    op.add_column("raw_fetches", sa.Column("provider_request_uuid", sa.Uuid(), nullable=True))
    op.execute("""
        INSERT INTO provider_requests (
            provider_request_uuid, provider, endpoint, query_parameters, status,
            requested_at, completed_at, response_status
        )
        SELECT
            raw_fetch_uuid, provider, endpoint, '{}'::jsonb, 'succeeded',
            fetched_at, fetched_at, response_status
        FROM raw_fetches
    """)
    op.execute("UPDATE raw_fetches SET provider_request_uuid = raw_fetch_uuid")
    op.alter_column("raw_fetches", "provider_request_uuid", nullable=False)
    op.drop_constraint(op.f("uq_raw_fetches_provider"), "raw_fetches", type_="unique")
    op.create_unique_constraint(op.f("uq_raw_fetches_object_key"), "raw_fetches", ["object_key"])
    op.create_unique_constraint(
        op.f("uq_raw_fetches_provider_request_uuid"), "raw_fetches", ["provider_request_uuid"]
    )
    op.create_foreign_key(
        op.f("fk_raw_fetches_provider_request_uuid_provider_requests"),
        "raw_fetches",
        "provider_requests",
        ["provider_request_uuid"],
        ["provider_request_uuid"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_raw_fetches_provider_request_uuid_provider_requests"),
        "raw_fetches",
        type_="foreignkey",
    )
    op.drop_constraint(op.f("uq_raw_fetches_provider_request_uuid"), "raw_fetches", type_="unique")
    op.drop_constraint(op.f("uq_raw_fetches_object_key"), "raw_fetches", type_="unique")
    op.create_unique_constraint(
        op.f("uq_raw_fetches_provider"),
        "raw_fetches",
        ["provider", "response_checksum"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("raw_fetches", "provider_request_uuid")
    op.drop_index(
        op.f("ix_competition_external_references_competition_uuid"),
        table_name="competition_external_references",
    )
    op.drop_table("competition_external_references")
    op.drop_index(op.f("ix_provider_requests_status"), table_name="provider_requests")
    op.drop_index(op.f("ix_provider_requests_provider"), table_name="provider_requests")
    op.drop_table("provider_requests")
    op.drop_index(
        "uq_identity_review_pending_external",
        table_name="identity_review_cases",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_identity_review_cases_status"), table_name="identity_review_cases")
    op.drop_table("identity_review_cases")
    op.execute("DROP TYPE provider_request_status")
    op.execute("DROP TYPE identity_review_status")
    # ### end Alembic commands ###
