"""create core domain schema

Revision ID: 8867eff66966
Revises:
Create Date: 2026-08-07 11:13:47.437457
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8867eff66966"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clubs",
        sa.Column("club_uuid", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=160), nullable=False),
        sa.Column("short_name", sa.String(length=80), nullable=False),
        sa.Column("crest_url", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("club_uuid", name=op.f("pk_clubs")),
        sa.UniqueConstraint("canonical_name", name=op.f("uq_clubs_canonical_name")),
    )
    op.create_table(
        "competitions",
        sa.Column("competition_uuid", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("rules_version", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("competition_uuid", name=op.f("pk_competitions")),
        sa.UniqueConstraint("slug", name=op.f("uq_competitions_slug")),
    )
    op.create_table(
        "lifecycle_events",
        sa.Column("event_uuid", sa.Uuid(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=60), nullable=False),
        sa.Column("aggregate_uuid", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("event_uuid", name=op.f("pk_lifecycle_events")),
    )
    op.create_index(
        op.f("ix_lifecycle_events_aggregate_type"),
        "lifecycle_events",
        ["aggregate_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lifecycle_events_aggregate_uuid"),
        "lifecycle_events",
        ["aggregate_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lifecycle_events_event_type"), "lifecycle_events", ["event_type"], unique=False
    )
    op.create_table(
        "players",
        sa.Column("player_uuid", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=180), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("nationality_code", sa.String(length=3), nullable=True),
        sa.Column("photo_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("player_uuid", name=op.f("pk_players")),
    )
    op.create_index(op.f("ix_players_canonical_name"), "players", ["canonical_name"], unique=False)
    op.create_table(
        "provider_request_budgets",
        sa.Column("budget_uuid", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("budget_date", sa.Date(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("operational_limit", sa.Integer(), nullable=False),
        sa.Column("hard_limit", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "request_count >= 0 AND operational_limit > 0 "
            "AND hard_limit >= operational_limit AND request_count <= hard_limit",
            name=op.f("ck_provider_request_budgets_valid_budget"),
        ),
        sa.PrimaryKeyConstraint("budget_uuid", name=op.f("pk_provider_request_budgets")),
        sa.UniqueConstraint(
            "provider", "budget_date", name=op.f("uq_provider_request_budgets_provider")
        ),
    )
    op.create_table(
        "raw_fetches",
        sa.Column("raw_fetch_uuid", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("endpoint", sa.String(length=240), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("response_status", sa.SmallInteger(), nullable=False),
        sa.Column("response_checksum", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("raw_fetch_uuid", name=op.f("pk_raw_fetches")),
        sa.UniqueConstraint("provider", "response_checksum", name=op.f("uq_raw_fetches_provider")),
    )
    op.create_index(op.f("ix_raw_fetches_provider"), "raw_fetches", ["provider"], unique=False)
    op.create_table(
        "club_external_references",
        sa.Column("reference_uuid", sa.Uuid(), nullable=False),
        sa.Column("club_uuid", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_club_id", sa.String(length=120), nullable=False),
        sa.Column("observed_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["club_uuid"],
            ["clubs.club_uuid"],
            name=op.f("fk_club_external_references_club_uuid_clubs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("reference_uuid", name=op.f("pk_club_external_references")),
        sa.UniqueConstraint(
            "provider", "external_club_id", name=op.f("uq_club_external_references_provider")
        ),
    )
    op.create_index(
        op.f("ix_club_external_references_club_uuid"),
        "club_external_references",
        ["club_uuid"],
        unique=False,
    )
    op.create_table(
        "player_external_references",
        sa.Column("reference_uuid", sa.Uuid(), nullable=False),
        sa.Column("player_uuid", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_player_id", sa.String(length=120), nullable=False),
        sa.Column("observed_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_uuid"],
            ["players.player_uuid"],
            name=op.f("fk_player_external_references_player_uuid_players"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("reference_uuid", name=op.f("pk_player_external_references")),
        sa.UniqueConstraint(
            "provider", "external_player_id", name=op.f("uq_player_external_references_provider")
        ),
    )
    op.create_index(
        op.f("ix_player_external_references_player_uuid"),
        "player_external_references",
        ["player_uuid"],
        unique=False,
    )
    op.create_table(
        "seasons",
        sa.Column("season_uuid", sa.Uuid(), nullable=False),
        sa.Column("competition_uuid", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_date > start_date", name=op.f("ck_seasons_date_order")),
        sa.ForeignKeyConstraint(
            ["competition_uuid"],
            ["competitions.competition_uuid"],
            name=op.f("fk_seasons_competition_uuid_competitions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("season_uuid", name=op.f("pk_seasons")),
        sa.UniqueConstraint("competition_uuid", "label", name=op.f("uq_seasons_competition_uuid")),
    )
    op.create_index(
        op.f("ix_seasons_competition_uuid"), "seasons", ["competition_uuid"], unique=False
    )
    op.create_table(
        "matches",
        sa.Column("match_uuid", sa.Uuid(), nullable=False),
        sa.Column("season_uuid", sa.Uuid(), nullable=False),
        sa.Column("home_club_uuid", sa.Uuid(), nullable=False),
        sa.Column("away_club_uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "postponed",
                "cancelled",
                "started",
                "suspended",
                "finished",
                "abandoned",
                "awarded",
                name="fixture_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "identity_review_state",
            sa.Enum("resolved", "needs_review", name="identity_review_state"),
            nullable=False,
        ),
        sa.Column("current_kickoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prediction_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "home_club_uuid <> away_club_uuid", name=op.f("ck_matches_different_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["away_club_uuid"],
            ["clubs.club_uuid"],
            name=op.f("fk_matches_away_club_uuid_clubs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["home_club_uuid"],
            ["clubs.club_uuid"],
            name=op.f("fk_matches_home_club_uuid_clubs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["season_uuid"],
            ["seasons.season_uuid"],
            name=op.f("fk_matches_season_uuid_seasons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("match_uuid", name=op.f("pk_matches")),
    )
    op.create_index(op.f("ix_matches_away_club_uuid"), "matches", ["away_club_uuid"], unique=False)
    op.create_index(
        op.f("ix_matches_current_kickoff_at"), "matches", ["current_kickoff_at"], unique=False
    )
    op.create_index(op.f("ix_matches_home_club_uuid"), "matches", ["home_club_uuid"], unique=False)
    op.create_index(
        op.f("ix_matches_prediction_due_at"), "matches", ["prediction_due_at"], unique=False
    )
    op.create_index(
        "ix_matches_season_kickoff", "matches", ["season_uuid", "current_kickoff_at"], unique=False
    )
    op.create_index(op.f("ix_matches_season_uuid"), "matches", ["season_uuid"], unique=False)
    op.create_table(
        "season_clubs",
        sa.Column("season_club_uuid", sa.Uuid(), nullable=False),
        sa.Column("season_uuid", sa.Uuid(), nullable=False),
        sa.Column("club_uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["club_uuid"],
            ["clubs.club_uuid"],
            name=op.f("fk_season_clubs_club_uuid_clubs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["season_uuid"],
            ["seasons.season_uuid"],
            name=op.f("fk_season_clubs_season_uuid_seasons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("season_club_uuid", name=op.f("pk_season_clubs")),
        sa.UniqueConstraint("season_uuid", "club_uuid", name=op.f("uq_season_clubs_season_uuid")),
    )
    op.create_index(op.f("ix_season_clubs_club_uuid"), "season_clubs", ["club_uuid"], unique=False)
    op.create_index(
        op.f("ix_season_clubs_season_uuid"), "season_clubs", ["season_uuid"], unique=False
    )
    op.create_table(
        "squad_memberships",
        sa.Column("membership_uuid", sa.Uuid(), nullable=False),
        sa.Column("season_uuid", sa.Uuid(), nullable=False),
        sa.Column("club_uuid", sa.Uuid(), nullable=False),
        sa.Column("player_uuid", sa.Uuid(), nullable=False),
        sa.Column("joined_on", sa.Date(), nullable=False),
        sa.Column("left_on", sa.Date(), nullable=True),
        sa.Column("shirt_number", sa.SmallInteger(), nullable=True),
        sa.Column("primary_position", sa.String(length=40), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "left_on IS NULL OR left_on >= joined_on",
            name=op.f("ck_squad_memberships_membership_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["club_uuid"],
            ["clubs.club_uuid"],
            name=op.f("fk_squad_memberships_club_uuid_clubs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_uuid"],
            ["players.player_uuid"],
            name=op.f("fk_squad_memberships_player_uuid_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["season_uuid"],
            ["seasons.season_uuid"],
            name=op.f("fk_squad_memberships_season_uuid_seasons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("membership_uuid", name=op.f("pk_squad_memberships")),
    )
    op.create_index(
        op.f("ix_squad_memberships_club_uuid"), "squad_memberships", ["club_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_squad_memberships_player_uuid"), "squad_memberships", ["player_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_squad_memberships_season_uuid"), "squad_memberships", ["season_uuid"], unique=False
    )
    op.create_table(
        "standings_snapshots",
        sa.Column("snapshot_uuid", sa.Uuid(), nullable=False),
        sa.Column("season_uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("real", "simulated", "fair_comparison", name="standings_kind"),
            nullable=False,
        ),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("calculation_version", sa.String(length=80), nullable=False),
        sa.Column("source_fixture_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season_uuid"],
            ["seasons.season_uuid"],
            name=op.f("fk_standings_snapshots_season_uuid_seasons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("snapshot_uuid", name=op.f("pk_standings_snapshots")),
        sa.UniqueConstraint(
            "season_uuid", "kind", "as_of", name=op.f("uq_standings_snapshots_season_uuid")
        ),
    )
    op.create_index(
        op.f("ix_standings_snapshots_season_uuid"),
        "standings_snapshots",
        ["season_uuid"],
        unique=False,
    )
    op.create_table(
        "actual_result_revisions",
        sa.Column("actual_result_uuid", sa.Uuid(), nullable=False),
        sa.Column("match_uuid", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("home_goals", sa.SmallInteger(), nullable=False),
        sa.Column("away_goals", sa.SmallInteger(), nullable=False),
        sa.Column(
            "result_kind",
            sa.Enum("regular", "abandoned_accepted", "awarded", name="result_kind"),
            nullable=False,
        ),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("provider_payload_key", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "home_goals >= 0 AND away_goals >= 0",
            name=op.f("ck_actual_result_revisions_nonnegative_score"),
        ),
        sa.ForeignKeyConstraint(
            ["match_uuid"],
            ["matches.match_uuid"],
            name=op.f("fk_actual_result_revisions_match_uuid_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("actual_result_uuid", name=op.f("pk_actual_result_revisions")),
        sa.UniqueConstraint(
            "match_uuid", "revision_number", name=op.f("uq_actual_result_revisions_match_uuid")
        ),
    )
    op.create_index(
        op.f("ix_actual_result_revisions_match_uuid"),
        "actual_result_revisions",
        ["match_uuid"],
        unique=False,
    )
    op.create_index(
        "uq_actual_result_accepted",
        "actual_result_revisions",
        ["match_uuid"],
        unique=True,
        postgresql_where=sa.text("accepted IS TRUE"),
    )
    op.create_table(
        "fixture_schedule_revisions",
        sa.Column("revision_uuid", sa.Uuid(), nullable=False),
        sa.Column("match_uuid", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("kickoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "canonical_status",
            sa.Enum(
                "scheduled",
                "postponed",
                "cancelled",
                "started",
                "suspended",
                "finished",
                "abandoned",
                "awarded",
                name="fixture_status",
            ),
            nullable=False,
        ),
        sa.Column("provider_status", sa.String(length=80), nullable=True),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_uuid"],
            ["matches.match_uuid"],
            name=op.f("fk_fixture_schedule_revisions_match_uuid_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("revision_uuid", name=op.f("pk_fixture_schedule_revisions")),
        sa.UniqueConstraint(
            "match_uuid", "revision_number", name=op.f("uq_fixture_schedule_revisions_match_uuid")
        ),
    )
    op.create_index(
        op.f("ix_fixture_schedule_revisions_match_uuid"),
        "fixture_schedule_revisions",
        ["match_uuid"],
        unique=False,
    )
    op.create_index(
        "uq_fixture_schedule_current",
        "fixture_schedule_revisions",
        ["match_uuid"],
        unique=True,
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.create_table(
        "job_runs",
        sa.Column("job_uuid", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=240), nullable=False),
        sa.Column("job_type", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "leased",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="job_status",
            ),
            nullable=False,
        ),
        sa.Column("match_uuid", sa.Uuid(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_job_runs_nonnegative_attempts")),
        sa.ForeignKeyConstraint(
            ["match_uuid"],
            ["matches.match_uuid"],
            name=op.f("fk_job_runs_match_uuid_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("job_uuid", name=op.f("pk_job_runs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_job_runs_idempotency_key")),
    )
    op.create_index(op.f("ix_job_runs_due_at"), "job_runs", ["due_at"], unique=False)
    op.create_index(op.f("ix_job_runs_job_type"), "job_runs", ["job_type"], unique=False)
    op.create_index(op.f("ix_job_runs_match_uuid"), "job_runs", ["match_uuid"], unique=False)
    op.create_index(op.f("ix_job_runs_status"), "job_runs", ["status"], unique=False)
    op.create_table(
        "match_external_references",
        sa.Column("reference_uuid", sa.Uuid(), nullable=False),
        sa.Column("match_uuid", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_fixture_id", sa.String(length=120), nullable=False),
        sa.Column("observed_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_uuid"],
            ["matches.match_uuid"],
            name=op.f("fk_match_external_references_match_uuid_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("reference_uuid", name=op.f("pk_match_external_references")),
        sa.UniqueConstraint(
            "provider", "external_fixture_id", name=op.f("uq_match_external_references_provider")
        ),
    )
    op.create_index(
        op.f("ix_match_external_references_match_uuid"),
        "match_external_references",
        ["match_uuid"],
        unique=False,
    )
    op.create_table(
        "prediction_versions",
        sa.Column("prediction_version_uuid", sa.Uuid(), nullable=False),
        sa.Column("match_uuid", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "generating",
                "active_locked",
                "voided",
                "evaluated",
                "failed",
                name="prediction_state",
            ),
            nullable=False,
        ),
        sa.Column("feature_cutoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=120), nullable=False),
        sa.Column("feature_snapshot_checksum", sa.String(length=64), nullable=False),
        sa.Column("home_win_probability", sa.Numeric(precision=9, scale=8), nullable=False),
        sa.Column("draw_probability", sa.Numeric(precision=9, scale=8), nullable=False),
        sa.Column("away_win_probability", sa.Numeric(precision=9, scale=8), nullable=False),
        sa.Column("expected_home_goals", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("expected_away_goals", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column(
            "statistics_distribution", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("void_reason", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expected_home_goals >= 0 AND expected_away_goals >= 0",
            name=op.f("ck_prediction_versions_nonnegative_xg"),
        ),
        sa.CheckConstraint(
            "home_win_probability + draw_probability + away_win_probability "
            "BETWEEN 0.999999 AND 1.000001",
            name=op.f("ck_prediction_versions_probability_sum"),
        ),
        sa.CheckConstraint(
            "home_win_probability >= 0 AND draw_probability >= 0 AND away_win_probability >= 0",
            name=op.f("ck_prediction_versions_nonnegative_probabilities"),
        ),
        sa.ForeignKeyConstraint(
            ["match_uuid"],
            ["matches.match_uuid"],
            name=op.f("fk_prediction_versions_match_uuid_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("prediction_version_uuid", name=op.f("pk_prediction_versions")),
        sa.UniqueConstraint(
            "match_uuid", "version_number", name=op.f("uq_prediction_versions_match_uuid")
        ),
    )
    op.create_index(
        op.f("ix_prediction_versions_match_uuid"),
        "prediction_versions",
        ["match_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prediction_versions_state"), "prediction_versions", ["state"], unique=False
    )
    op.create_index(
        "uq_prediction_versions_active_match",
        "prediction_versions",
        ["match_uuid"],
        unique=True,
        postgresql_where=sa.text("state IN ('active_locked', 'evaluated')"),
    )
    op.create_table(
        "standings_rows",
        sa.Column("standings_row_uuid", sa.Uuid(), nullable=False),
        sa.Column("snapshot_uuid", sa.Uuid(), nullable=False),
        sa.Column("club_uuid", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("played", sa.SmallInteger(), nullable=False),
        sa.Column("won", sa.SmallInteger(), nullable=False),
        sa.Column("drawn", sa.SmallInteger(), nullable=False),
        sa.Column("lost", sa.SmallInteger(), nullable=False),
        sa.Column("goals_for", sa.SmallInteger(), nullable=False),
        sa.Column("goals_against", sa.SmallInteger(), nullable=False),
        sa.Column("goal_difference", sa.SmallInteger(), nullable=False),
        sa.Column("points", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint(
            "position > 0 AND played >= 0 AND points >= 0",
            name=op.f("ck_standings_rows_valid_totals"),
        ),
        sa.CheckConstraint(
            "won + drawn + lost = played", name=op.f("ck_standings_rows_result_total")
        ),
        sa.ForeignKeyConstraint(
            ["club_uuid"],
            ["clubs.club_uuid"],
            name=op.f("fk_standings_rows_club_uuid_clubs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_uuid"],
            ["standings_snapshots.snapshot_uuid"],
            name=op.f("fk_standings_rows_snapshot_uuid_standings_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("standings_row_uuid", name=op.f("pk_standings_rows")),
        sa.UniqueConstraint("snapshot_uuid", "club_uuid", name="uq_standings_rows_snapshot_club"),
        sa.UniqueConstraint(
            "snapshot_uuid", "position", name="uq_standings_rows_snapshot_position"
        ),
    )
    op.create_index(
        op.f("ix_standings_rows_club_uuid"), "standings_rows", ["club_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_standings_rows_snapshot_uuid"), "standings_rows", ["snapshot_uuid"], unique=False
    )
    op.create_table(
        "predicted_lineups",
        sa.Column("predicted_lineup_uuid", sa.Uuid(), nullable=False),
        sa.Column("prediction_version_uuid", sa.Uuid(), nullable=False),
        sa.Column("formation", sa.String(length=20), nullable=False),
        sa.Column("lineup_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["prediction_version_uuid"],
            ["prediction_versions.prediction_version_uuid"],
            name=op.f("fk_predicted_lineups_prediction_version_uuid_prediction_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("predicted_lineup_uuid", name=op.f("pk_predicted_lineups")),
        sa.UniqueConstraint(
            "prediction_version_uuid", name=op.f("uq_predicted_lineups_prediction_version_uuid")
        ),
    )
    op.create_table(
        "stored_simulations",
        sa.Column("simulation_uuid", sa.Uuid(), nullable=False),
        sa.Column("prediction_version_uuid", sa.Uuid(), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("home_goals", sa.SmallInteger(), nullable=False),
        sa.Column("away_goals", sa.SmallInteger(), nullable=False),
        sa.Column("statistics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "home_goals >= 0 AND away_goals >= 0",
            name=op.f("ck_stored_simulations_nonnegative_score"),
        ),
        sa.ForeignKeyConstraint(
            ["prediction_version_uuid"],
            ["prediction_versions.prediction_version_uuid"],
            name=op.f("fk_stored_simulations_prediction_version_uuid_prediction_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("simulation_uuid", name=op.f("pk_stored_simulations")),
        sa.UniqueConstraint(
            "prediction_version_uuid", name=op.f("uq_stored_simulations_prediction_version_uuid")
        ),
    )
    op.execute("""
        CREATE FUNCTION protect_locked_prediction_payload() RETURNS trigger AS $$
        BEGIN
            IF OLD.state IN ('active_locked', 'evaluated', 'voided') AND (
                NEW.match_uuid IS DISTINCT FROM OLD.match_uuid OR
                NEW.version_number IS DISTINCT FROM OLD.version_number OR
                NEW.feature_cutoff_at IS DISTINCT FROM OLD.feature_cutoff_at OR
                NEW.model_version IS DISTINCT FROM OLD.model_version OR
                NEW.feature_snapshot_checksum IS DISTINCT FROM OLD.feature_snapshot_checksum OR
                NEW.home_win_probability IS DISTINCT FROM OLD.home_win_probability OR
                NEW.draw_probability IS DISTINCT FROM OLD.draw_probability OR
                NEW.away_win_probability IS DISTINCT FROM OLD.away_win_probability OR
                NEW.expected_home_goals IS DISTINCT FROM OLD.expected_home_goals OR
                NEW.expected_away_goals IS DISTINCT FROM OLD.expected_away_goals OR
                NEW.statistics_distribution IS DISTINCT FROM OLD.statistics_distribution OR
                NEW.locked_at IS DISTINCT FROM OLD.locked_at
            ) THEN
                RAISE EXCEPTION 'locked prediction payloads are immutable';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER trg_prediction_payload_immutable
        BEFORE UPDATE ON prediction_versions
        FOR EACH ROW EXECUTE FUNCTION protect_locked_prediction_payload()
    """)
    op.execute("""
        CREATE FUNCTION protect_prediction_artifact() RETURNS trigger AS $$
        DECLARE owner_state prediction_state;
        BEGIN
            SELECT state INTO owner_state
            FROM prediction_versions
            WHERE prediction_version_uuid = OLD.prediction_version_uuid;
            IF owner_state IN ('active_locked', 'evaluated', 'voided') THEN
                RAISE EXCEPTION 'artifacts belonging to locked predictions are immutable';
            END IF;
            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER trg_predicted_lineup_immutable
        BEFORE UPDATE OR DELETE ON predicted_lineups
        FOR EACH ROW EXECUTE FUNCTION protect_prediction_artifact()
    """)
    op.execute("""
        CREATE TRIGGER trg_stored_simulation_immutable
        BEFORE UPDATE OR DELETE ON stored_simulations
        FOR EACH ROW EXECUTE FUNCTION protect_prediction_artifact()
    """)
    op.execute("""
        CREATE FUNCTION lifecycle_events_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'lifecycle events are append-only';
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER trg_lifecycle_events_append_only
        BEFORE UPDATE OR DELETE ON lifecycle_events
        FOR EACH ROW EXECUTE FUNCTION lifecycle_events_append_only()
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER trg_lifecycle_events_append_only ON lifecycle_events")
    op.execute("DROP FUNCTION lifecycle_events_append_only()")
    op.execute("DROP TRIGGER trg_stored_simulation_immutable ON stored_simulations")
    op.execute("DROP TRIGGER trg_predicted_lineup_immutable ON predicted_lineups")
    op.execute("DROP FUNCTION protect_prediction_artifact()")
    op.execute("DROP TRIGGER trg_prediction_payload_immutable ON prediction_versions")
    op.execute("DROP FUNCTION protect_locked_prediction_payload()")
    op.drop_table("stored_simulations")
    op.drop_table("predicted_lineups")
    op.drop_index(op.f("ix_standings_rows_snapshot_uuid"), table_name="standings_rows")
    op.drop_index(op.f("ix_standings_rows_club_uuid"), table_name="standings_rows")
    op.drop_table("standings_rows")
    op.drop_index(
        "uq_prediction_versions_active_match",
        table_name="prediction_versions",
        postgresql_where=sa.text("state IN ('active_locked', 'evaluated')"),
    )
    op.drop_index(op.f("ix_prediction_versions_state"), table_name="prediction_versions")
    op.drop_index(op.f("ix_prediction_versions_match_uuid"), table_name="prediction_versions")
    op.drop_table("prediction_versions")
    op.drop_index(
        op.f("ix_match_external_references_match_uuid"), table_name="match_external_references"
    )
    op.drop_table("match_external_references")
    op.drop_index(op.f("ix_job_runs_status"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_match_uuid"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_job_type"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_due_at"), table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_index(
        "uq_fixture_schedule_current",
        table_name="fixture_schedule_revisions",
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_fixture_schedule_revisions_match_uuid"), table_name="fixture_schedule_revisions"
    )
    op.drop_table("fixture_schedule_revisions")
    op.drop_index(
        "uq_actual_result_accepted",
        table_name="actual_result_revisions",
        postgresql_where=sa.text("accepted IS TRUE"),
    )
    op.drop_index(
        op.f("ix_actual_result_revisions_match_uuid"), table_name="actual_result_revisions"
    )
    op.drop_table("actual_result_revisions")
    op.drop_index(op.f("ix_standings_snapshots_season_uuid"), table_name="standings_snapshots")
    op.drop_table("standings_snapshots")
    op.drop_index(op.f("ix_squad_memberships_season_uuid"), table_name="squad_memberships")
    op.drop_index(op.f("ix_squad_memberships_player_uuid"), table_name="squad_memberships")
    op.drop_index(op.f("ix_squad_memberships_club_uuid"), table_name="squad_memberships")
    op.drop_table("squad_memberships")
    op.drop_index(op.f("ix_season_clubs_season_uuid"), table_name="season_clubs")
    op.drop_index(op.f("ix_season_clubs_club_uuid"), table_name="season_clubs")
    op.drop_table("season_clubs")
    op.drop_index(op.f("ix_matches_season_uuid"), table_name="matches")
    op.drop_index("ix_matches_season_kickoff", table_name="matches")
    op.drop_index(op.f("ix_matches_prediction_due_at"), table_name="matches")
    op.drop_index(op.f("ix_matches_home_club_uuid"), table_name="matches")
    op.drop_index(op.f("ix_matches_current_kickoff_at"), table_name="matches")
    op.drop_index(op.f("ix_matches_away_club_uuid"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_seasons_competition_uuid"), table_name="seasons")
    op.drop_table("seasons")
    op.drop_index(
        op.f("ix_player_external_references_player_uuid"), table_name="player_external_references"
    )
    op.drop_table("player_external_references")
    op.drop_index(
        op.f("ix_club_external_references_club_uuid"), table_name="club_external_references"
    )
    op.drop_table("club_external_references")
    op.drop_index(op.f("ix_raw_fetches_provider"), table_name="raw_fetches")
    op.drop_table("raw_fetches")
    op.drop_table("provider_request_budgets")
    op.drop_index(op.f("ix_players_canonical_name"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_lifecycle_events_event_type"), table_name="lifecycle_events")
    op.drop_index(op.f("ix_lifecycle_events_aggregate_uuid"), table_name="lifecycle_events")
    op.drop_index(op.f("ix_lifecycle_events_aggregate_type"), table_name="lifecycle_events")
    op.drop_table("lifecycle_events")
    op.drop_table("competitions")
    op.drop_table("clubs")
    op.execute("DROP TYPE prediction_state")
    op.execute("DROP TYPE job_status")
    op.execute("DROP TYPE result_kind")
    op.execute("DROP TYPE standings_kind")
    op.execute("DROP TYPE identity_review_state")
    op.execute("DROP TYPE fixture_status")
    # ### end Alembic commands ###
